### PR TITLE
Changed publication to check for field limiters

### PR DESCRIPTION
**Pull request by kantle**
When enriching activities, the publication now checked for a object called Stream.publishFields, which is defined on the Server. The object contains a list of whitelisted fields to publish on the cursor. If this object or the model within the object does not exist, all fields are published.

Example usecase would be:

Stream.publishFields = {
  users: {
    profile: 1,
  }
}

### CODE REVIEW

**Comment by matthisk** [comment]
Wouldn't it be nicer if you supply the `publishFields` to `Stream.registerActivity`. Then we avoid appending a property to the global namespace of the package (something that might not work in the future if we switch to ES6 module syntax) and you are able to customize the field enrichment publication per registered collection, what are your thoughts on this?

**Comment by kantle** [comment]
I'm actually not using Stream.registerActivity, I'm just using the lower level addActivity function. When you use registerActivity, it creates an activity record upon inserting a document into the collection. For most of my activities I want to add, either there is no document being inserted into a collection, or I don't want to create the activity on document insert, but rather on update. For example, when a user creates a post, I insert the draft into the posts collection, but I don't want to create the activity until the user publishes the post (in my app this is accomplished by changing the status from draft to published). So I use a collection hook on the update to check to see if the status has changed, then I call addActivity.

When I add the activity this way, I still supply the name of the collection in to object field like below:

var userFeed = Stream.feedManager.getUserFeed(userId);
    var activity = {
      actor: 'users:' + userId,
      verb: 'post',
      object: 'posts'+ doc._id,
      foreign_id: userId + ':' + doc._id,
    };
    userFeed.addActivity(activity);

When I access this activity through Stream.feeds.user synthetic collection, the package still enriches the record with the document from the respective collection (in the above case it will add the user object and the post document.

Since I wasn't using registerCollection I had to create the Stream.publishFields property.

**Comment by matthisk** [comment]
Ok that makes sense, then I get why you decided to expose it on a global variable. I still think we should not set the `publishFields` as a property on the `Stream` global, but use a method instead, thus `Stream.setPublishFields({ /* .... */ })` this way we can port this feature easily to ES6 module syntax. Your usecase sound valid and I can imagine other people having a similar approach to the link between collections and activities. It could be interesting to add functionality you describe natively to the [collections manager](https://github.com/GetStream/stream-meteor/blob/master/src/collections.js), we could create a hook on update, check if some condition is true, and publish the activitiy.

**Comment by kantle** [comment]
Sure that makes sense - I just changed my fork to use a setPublishFields function instead.
I could see how you add a update hook to collections manager, you'd probably need to add some options for enabling/disabling activity creation for insert and remove. Maybe expose functions for addActivityOnInsert, addActivityOnUpdate, addActivityOnRemove. Then I could just return false for addActivityOnInsert (or default to true if the user does not define a function). Similarly for addActivityOnUpdate I could use my own logic to determine if I want to add the activity (in my use case I would compare the doc and the modifier) and then return true (or false).

Just another thought but I noticed you are currently using the "after" insert and remove hooks - I specifically needed to use the "before" update hook in order to see if a particular change has occurred (status changed from draft to published).

**Pull request merged**
